// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Data;

#nullable disable

namespace Backend.src.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260216213513_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebApp.Generated.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("BookingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("booking_date")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("BookingReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("booking_reference");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("email");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("int")
                        .HasColumnName("screening_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending','accepted','cancelled')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'");

                    b.Property<decimal?>("TotalPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_price")
                        .HasDefaultValueSql("'0.00'");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BookingReference" }, "booking_reference")
                        .IsUnique();

                    b.HasIndex(new[] { "ScreeningId" }, "screening_id");

                    b.HasIndex(new[] { "UserId" }, "user_id");

                    b.ToTable("booking");
                });

            modelBuilder.Entity("WebApp.Generated.BookingSeat", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<int>("SeatId")
                        .HasColumnType("int")
                        .HasColumnName("seat_id");

                    b.Property<decimal>("FinalPrice")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("final_price");

                    b.Property<int>("PriceCategorySeatId")
                        .HasColumnType("int")
                        .HasColumnName("price_category_seat_id");

                    b.HasKey("BookingId", "SeatId")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.HasIndex(new[] { "PriceCategorySeatId" }, "price_category_seat_id");

                    b.HasIndex(new[] { "SeatId" }, "seat_id");

                    b.ToTable("booking_seat");
                });

            modelBuilder.Entity("WebApp.Generated.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("enum('Action','Äventyr','Komedi','Drama','Skräck','Science Fiction','Thriller','Fantasy','Romantik','Western','Krig','Musikal','Dokumentär','Animerat')")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("genre");
                });

            modelBuilder.Entity("WebApp.Generated.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("RowCount")
                        .HasColumnType("int")
                        .HasColumnName("row_count");

                    b.Property<short>("ScreenSize")
                        .HasColumnType("smallint")
                        .HasColumnName("screen_size");

                    b.Property<int>("SoundSystem")
                        .HasColumnType("int")
                        .HasColumnName("sound_system");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "SoundSystem" }, "sound_system");

                    b.HasIndex(new[] { "Type" }, "type");

                    b.ToTable("hall");
                });

            modelBuilder.Entity("WebApp.Generated.HallRowConfig", b =>
                {
                    b.Property<int>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("hall_id");

                    b.Property<string>("Name")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("name");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int")
                        .HasColumnName("number_of_seats");

                    b.HasKey("HallId", "Name")
                        .HasName("PRIMARY")
                        .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

                    b.ToTable("hall_row_config");
                });

            modelBuilder.Entity("WebApp.Generated.HallType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Standard','IMAX','4DX','Dolby Cinema','iSense','3D')")
                        .HasColumnName("type")
                        .HasDefaultValueSql("'Standard'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("hall_type");
                });

            modelBuilder.Entity("WebApp.Generated.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeRating")
                        .IsRequired()
                        .HasColumnType("enum('B','7','11','15')")
                        .HasColumnName("age_rating");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DescriptionShort")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("description_short");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("director");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("duration_minutes");

                    b.Property<int>("Language")
                        .HasColumnType("int")
                        .HasColumnName("language");

                    b.Property<string>("Poster")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("poster");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Language" }, "language");

                    b.ToTable("movie");
                });

            modelBuilder.Entity("WebApp.Generated.MovieLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MovieLangEnum")
                        .IsRequired()
                        .HasColumnType("enum('Svenska','Engelska')")
                        .HasColumnName("movie_lang_enum");

                    b.Property<string>("MovieLangShortEnum")
                        .IsRequired()
                        .HasColumnType("enum('Sv','En')")
                        .HasColumnName("movie_lang_short_enum");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("movie_language");
                });

            modelBuilder.Entity("WebApp.Generated.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("Status")
                        .HasColumnType("enum('pending','accepted','declined')")
                        .HasColumnName("status");

                    b.HasKey("PaymentId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BookingId" }, "booking_id");

                    b.ToTable("payment");
                });

            modelBuilder.Entity("WebApp.Generated.PriceCategorySeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("enum('Adult','Child','Senior','Student','Handicap')")
                        .HasColumnName("category");

                    b.Property<decimal?>("DiscountModifier")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discount_modifier")
                        .HasDefaultValueSql("'0.00'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("price_category_seat");
                });

            modelBuilder.Entity("WebApp.Generated.Screening", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BasePrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("base_price")
                        .HasDefaultValueSql("'100.00'");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime")
                        .HasColumnName("end_time");

                    b.Property<int>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("hall_id");

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("movie_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime")
                        .HasColumnName("start_time");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "HallId" }, "hall_id");

                    b.HasIndex(new[] { "MovieId" }, "movie_id");

                    b.ToTable("screening");
                });

            modelBuilder.Entity("WebApp.Generated.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HallId")
                        .HasColumnType("int")
                        .HasColumnName("hall_id");

                    b.Property<int>("NumberInRow")
                        .HasColumnType("int")
                        .HasColumnName("number_in_row");

                    b.Property<string>("RowName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("row_name");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Type" }, "type")
                        .HasDatabaseName("type1");

                    b.HasIndex(new[] { "HallId", "RowName", "NumberInRow" }, "unique_seat_id")
                        .IsUnique();

                    b.ToTable("seat");
                });

            modelBuilder.Entity("WebApp.Generated.SeatGhost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("ReservedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("reserved_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("ScreeningId")
                        .HasColumnType("int")
                        .HasColumnName("screening_id");

                    b.Property<int>("SeatId")
                        .HasColumnType("int")
                        .HasColumnName("seat_id");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ScreeningId" }, "screening_id")
                        .HasDatabaseName("screening_id1");

                    b.HasIndex(new[] { "SeatId" }, "seat_id")
                        .HasDatabaseName("seat_id1");

                    b.ToTable("seat_ghost");
                });

            modelBuilder.Entity("WebApp.Generated.SeatType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Standard','Premium','VIP','Handicap','Recliner')")
                        .HasColumnName("name")
                        .HasDefaultValueSql("'Standard'");

                    b.Property<decimal?>("Surcharge")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("surcharge")
                        .HasDefaultValueSql("'0.00'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("seat_type");
                });

            modelBuilder.Entity("WebApp.Generated.SoundSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("system_name");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("sound_system");
                });

            modelBuilder.Entity("WebApp.Generated.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("created")
                        .HasDefaultValueSql("curdate()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("firstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("lastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role")
                        .HasDefaultValueSql("'user'");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "Email" }, "email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("WebApp.Generated.Booking", b =>
                {
                    b.HasOne("WebApp.Generated.Screening", "Screening")
                        .WithMany("Bookings")
                        .HasForeignKey("ScreeningId")
                        .IsRequired()
                        .HasConstraintName("booking_ibfk_1");

                    b.HasOne("WebApp.Generated.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("booking_ibfk_2");

                    b.Navigation("Screening");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApp.Generated.BookingSeat", b =>
                {
                    b.HasOne("WebApp.Generated.Booking", "Booking")
                        .WithMany("BookingSeats")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("booking_seat_ibfk_1");

                    b.HasOne("WebApp.Generated.PriceCategorySeat", "PriceCategorySeat")
                        .WithMany("BookingSeats")
                        .HasForeignKey("PriceCategorySeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("booking_seat_ibfk_3");

                    b.HasOne("WebApp.Generated.Seat", "Seat")
                        .WithMany("BookingSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("booking_seat_ibfk_2");

                    b.Navigation("Booking");

                    b.Navigation("PriceCategorySeat");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("WebApp.Generated.Hall", b =>
                {
                    b.HasOne("WebApp.Generated.SoundSystem", "SoundSystemNavigation")
                        .WithMany("Halls")
                        .HasForeignKey("SoundSystem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("hall_ibfk_1");

                    b.HasOne("WebApp.Generated.HallType", "TypeNavigation")
                        .WithMany("Halls")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("hall_ibfk_2");

                    b.Navigation("SoundSystemNavigation");

                    b.Navigation("TypeNavigation");
                });

            modelBuilder.Entity("WebApp.Generated.HallRowConfig", b =>
                {
                    b.HasOne("WebApp.Generated.Hall", "Hall")
                        .WithMany("HallRowConfigs")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("hall_row_config_ibfk_1");

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("WebApp.Generated.Movie", b =>
                {
                    b.HasOne("WebApp.Generated.MovieLanguage", "LanguageNavigation")
                        .WithMany("Movies")
                        .HasForeignKey("Language")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("movie_ibfk_1");

                    b.Navigation("LanguageNavigation");
                });

            modelBuilder.Entity("WebApp.Generated.Payment", b =>
                {
                    b.HasOne("WebApp.Generated.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("payment_ibfk_1");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("WebApp.Generated.Screening", b =>
                {
                    b.HasOne("WebApp.Generated.Hall", "Hall")
                        .WithMany("Screenings")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("screening_ibfk_2");

                    b.HasOne("WebApp.Generated.Movie", "Movie")
                        .WithMany("Screenings")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("screening_ibfk_1");

                    b.Navigation("Hall");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("WebApp.Generated.Seat", b =>
                {
                    b.HasOne("WebApp.Generated.SeatType", "TypeNavigation")
                        .WithMany("Seats")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("seat_ibfk_2");

                    b.HasOne("WebApp.Generated.HallRowConfig", "HallRowConfig")
                        .WithMany("Seats")
                        .HasForeignKey("HallId", "RowName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("seat_ibfk_1");

                    b.Navigation("HallRowConfig");

                    b.Navigation("TypeNavigation");
                });

            modelBuilder.Entity("WebApp.Generated.SeatGhost", b =>
                {
                    b.HasOne("WebApp.Generated.Screening", "Screening")
                        .WithMany("SeatGhosts")
                        .HasForeignKey("ScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("seat_ghost_ibfk_1");

                    b.HasOne("WebApp.Generated.Seat", "Seat")
                        .WithMany("SeatGhosts")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("seat_ghost_ibfk_2");

                    b.Navigation("Screening");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("WebApp.Generated.Booking", b =>
                {
                    b.Navigation("BookingSeats");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("WebApp.Generated.Hall", b =>
                {
                    b.Navigation("HallRowConfigs");

                    b.Navigation("Screenings");
                });

            modelBuilder.Entity("WebApp.Generated.HallRowConfig", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("WebApp.Generated.HallType", b =>
                {
                    b.Navigation("Halls");
                });

            modelBuilder.Entity("WebApp.Generated.Movie", b =>
                {
                    b.Navigation("Screenings");
                });

            modelBuilder.Entity("WebApp.Generated.MovieLanguage", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("WebApp.Generated.PriceCategorySeat", b =>
                {
                    b.Navigation("BookingSeats");
                });

            modelBuilder.Entity("WebApp.Generated.Screening", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("SeatGhosts");
                });

            modelBuilder.Entity("WebApp.Generated.Seat", b =>
                {
                    b.Navigation("BookingSeats");

                    b.Navigation("SeatGhosts");
                });

            modelBuilder.Entity("WebApp.Generated.SeatType", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("WebApp.Generated.SoundSystem", b =>
                {
                    b.Navigation("Halls");
                });

            modelBuilder.Entity("WebApp.Generated.User", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
